package br.com.diego.model;
// Generated Apr 24, 2013 3:07:29 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Comentario generated by hbm2java
 */
@Entity
@Table(name = "COMENTARIO")
public class Comentario implements java.io.Serializable {

    private int cdCliente;
    private String nmCliente;
    private String nmClienteEmail;
    private String nmClienteComentario;

    /**
     *
     */
    public Comentario() {
    }

    /**
     *
     * @param cdCliente
     */
    public Comentario(int cdCliente) {
        this.cdCliente = cdCliente;
    }

    /**
     *
     * @param nmCliente
     * @param nmClienteEmail
     * @param nmClienteComentario
     */
    public Comentario(String nmCliente, String nmClienteEmail,
            String nmClienteComentario) {

        this.nmCliente = nmCliente;
        this.nmClienteEmail = nmClienteEmail;
        this.nmClienteComentario = nmClienteComentario;
    }

    /**
     *
     * @return
     */
    @Id
    @GeneratedValue
    @Column(name = "CD_CLIENTE")
    public int getCdCliente() {
        return this.cdCliente;
    }

    /**
     *
     * @param cdCliente
     */
    public void setCdCliente(int cdCliente) {
        this.cdCliente = cdCliente;
    }

    /**
     *
     * @return
     */
    @Column(name = "NM_CLIENTE")
    public String getNmCliente() {
        return this.nmCliente;
    }

    /**
     *
     * @param nmCliente
     */
    public void setNmCliente(String nmCliente) {
        this.nmCliente = nmCliente;
    }

    /**
     *
     * @return
     */
    @Column(name = "NM_CLIENTE_EMAIL")
    public String getNmClienteEmail() {
        return this.nmClienteEmail;
    }

    /**
     *
     * @param nmClienteEmail
     */
    public void setNmClienteEmail(String nmClienteEmail) {
        this.nmClienteEmail = nmClienteEmail;
    }

    /**
     *
     * @return
     */
    @Column(name = "NM_CLIENTE_COMENTARIO")
    public String getNmClienteComentario() {
        return this.nmClienteComentario;
    }

    /**
     *
     * @param nmClienteComentario
     */
    public void setNmClienteComentario(String nmClienteComentario) {
        this.nmClienteComentario = nmClienteComentario;
    }
}
